server:
  port: 7001
eureka:
  instance:
    hostname: www.eureka7001.test
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7002.test:7002/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000